# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
# yaml-language-server: $schema=./meta-schema.yaml

title: OCI Kubernetes Monitoring Solution
description: "OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on the following OCI services: Logging Analytics, Monitoring, and Management Agent."
informationalText: "OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on the following OCI services: Logging Analytics, Monitoring, and Management Agent."
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: marketplace  # enum - marketplace, quickstart or web

locale: "en"

variableGroups:
  - title: "hidden inputs"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - private_key_path
      - fingerprint
      - boat_auth
      - boat_tenancy_ocid
      - toggle_generate_helm_template
      - toggle_install_helm
      - toggle_use_local_helm_chart
      - toggle_dashboards_module
      - toggle_helm_module
      - toggle_mgmt_agent_module
      - toggle_logan_module
      - toggle_livelab_module
      - toggle_iam_module
      - compartment_ocid
      - kubernetes_namespace
      - current_user_ocid
      - livelab_switch
      - oke_cluster_name
      - oke_cluster_entity_ocid
      - stack_deployment_option
    visible: false

  - title: Select an OKE cluster deployed in this region to start monitoring.
    description: "Use CLI (Helm) if your cluster does not have a public API endpoint or if it's restricted from accessing container-registry.oracle.com. See: https://github.com/oracle-quickstart/oci-kubernetes-monitoring"
    variables:
      - oke_compartment_ocid
      - oke_cluster_ocid

  - title: "OCI Observability and Management Services Configuration"
    description: "For a list of resources created, see: https://github.com/oracle-quickstart/oci-kubernetes-monitoring"
    variables:
    - opt_deploy_metric_server
    - oci_onm_compartment_ocid
    - opt_create_new_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name
    - fluentd_baseDir_path

  - title: OCI IAM Policies and Dynamic Groups (Optional)
    variables:
      - opt_create_dynamicGroup_and_policies

variables:

  ####
  ##  OKE Cluster Information
  ####

  # OKE Cluster Compartment
  oke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Select OKE cluster compartment"
    default: compartment_ocid

  # OKE Cluster OCID
  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_compartment_ocid}
    title: Select OKE cluster
    required: true

  # kubernetes_namespace:
  #   type: string
  #   minLength: 1
  #   maxLength: 63
  #   title: Kubernetes Namespace
  #   description: Kubernetes Namespace in which the monitoring solution to be deployed
  #   default: kube-system
  #   pattern: '^([a-z0-9]|[a-z][a-z\-0-9]*[a-z0-9])$' #Ref - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
  #   required: true

  ####
  ##  OCI Observability and Management Services Configuration
  ####

  #  Stack Deployment Options
  stack_deployment_option:
    title: Deployment options
    description: 'The "Full" option creates both OCI and K8s resources.'
    type: enum
    enum: # Dev Note - # Any change in following options must be refactored across schema.yaml
    - "Full"
    - "Only OCI Resources"
    default: "Full"
    required: true
    visible:
       not: 
       - livelab_switch    

  # Option to enable/disable metric server installation during helm deployment
  opt_deploy_metric_server:
    type: boolean
    title: Enable Metric Server installation
    description: Clear this check box if Metric Server is already installed in your cluster.
    default: true
    visible:
      and:
      - eq:
        - ${stack_deployment_option}
        - "Full"
      - not: 
        - livelab_switch

  # Compartment for creating OCI Observability and Management resources
  oci_onm_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Select compartment for Logging Analytics, Management Agent, and Monitoring service resources.
    description: "This compartment will be used for creating dashboards, log groups, entities, Management Agent keys, metric namespaces, and related resources. For a full list of resources, see: https://github.com/oracle-quickstart/oci-kubernetes-monitoring"
    default: compartment_ocid

  # Option to create Logging Analytics
  opt_create_new_la_logGroup: # change this to create new log group
    type: boolean
    title: Select this check box if you want to create a new log group.
    default: false
    visible:
      not: 
      - livelab_switch

  # OCI Logging Analytics LogGroup OCID of existing LogGroup
  oci_la_logGroup_id:
    type: oci:logan:loggroup:id
    dependsOn:
      compartmentId: ${oci_onm_compartment_ocid}
    title: OCI Logging Analytics log group
    description: Log groups are logical containers for log data, and they provide access control for your data using IAM policies.
    required: true
    visible:
      not:
        - opt_create_new_la_logGroup

  # New Log Group to collect Kubernetes data
  oci_la_logGroup_name:
    type: string
    maxLength: 255
    minLength: 1
    required: true
    title: OCI Logging Analytics log group name
    description: "Tip: To make the log group easy to find in Dashboards and Logs Explorer pages, provide a unique name associated with your cluster name."
    visible:
      and:
        - opt_create_new_la_logGroup
    pattern: '^([a-zA-Z0-9]|[a-zA-Z0-9][\\ a-zA-Z0-9_\-]*[\\a-zA-Z\-0-9_])$'  

  # Fluentd Base Directory
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: FluentD working directory
    description: A directory on the node (with read & write permission) to use for storing data related to Fluentd.
    default: /var/log
    required: true
    pattern: '^/[\w- /]*$'
    visible:
      and:
      - eq:
        - ${stack_deployment_option}
        - "Full"
      - not: 
        - livelab_switch

  ####
  ##  Pre-requisites
  ####

  # Option to create Dynamic Group and Policies
  opt_create_dynamicGroup_and_policies:
    type: boolean
    title: Select this check box to create dynamic groups and policies that are required for deploying the monitoring solution.
    #description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
    description: "Note: If node pools and the OKE cluster are in different compartments, then the dynamic group definition must be updated."
    default: false
    required: true    