# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.
# yaml-language-server: $schema=./meta-schema.yaml

title: OCI Kubernetes Monitoring Solution
description: OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on OCI Logging Analytics cloud service, OCI Monitoring, OCI Management Agent.
informationalText: OCI Kubernetes Monitoring Solution is a turn-key Kubernetes monitoring and management package based on OCI Logging Analytics cloud service, OCI Monitoring, OCI Management Agent.
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: marketplace  # enum - marketplace, quickstart or web

locale: "en"

variableGroups:
  - title: "hidden inputs"
    variables:
      - tenancy_ocid
      - region
      - user_ocid
      - private_key_path
      - fingerprint
      - boat_auth
      - boat_tenancy_ocid
      - dev_switch_generate_helm_template
      - dev_switch_dashboards_module
      - dev_switch_helm_module
      - dev_switch_mgmt_agent_module
      - dev_switch_logan_module
      - dev_switch_livelab_module
      - dev_switch_iam_module
      - compartment_ocid
      - logan_container_image_url
      - mgmt_agent_container_image_url
      - kubernetes_namespace
      - current_user_ocid
      - livelab_switch
      - triggered_by_add_data_flow
    visible: false

  - title: "Select an OKE Cluster deployed in this region to start monitoring"
    description: "Use CLI (Helm) if your cluster does not have public API Endpoint or restricted from accessing container-registry.oracle.com. See: https://github.com/oracle-quickstart/oci-kubernetes-monitoring"
    variables:
      - oke_compartment_ocid
      - oke_cluster_ocid

  - title: "OCI Observability & Management Services Configuration"
    description: "See: https://github.com/oracle-quickstart/oci-kubernetes-monitoring for list of resources created"
    variables:
    - oci_onm_compartment_ocid
    - opt_create_new_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name

  - title: "Kubernetes Deployment Configuration"
    variables:
      - opt_deploy_helm
      - opt_deploy_metric_server
      - fluentd_baseDir_path
    visible:
      not: 
        - livelab_switch

  - title: "OCI IAM Policies and Dynaimic Groups (Optional)"
    variables:
      - opt_create_dynamicGroup_and_policies

variables:

  ####
  ##  OKE Cluster Information
  ####

  # OKE Cluster Compartment
  oke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: "Select OKE Cluster Compartment"
    default: compartment_ocid

  # OKE Cluster OCID
  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_compartment_ocid}
    title: Select OKE Cluster
    required: true

  # kubernetes_namespace:
  #   type: string
  #   minLength: 1
  #   maxLength: 63
  #   title: Kubernetes Namespace
  #   description: Kubernetes Namespace in which the monitoring solution to be deployed
  #   default: kube-system
  #   pattern: '^([a-z0-9]|[a-z][a-z\-0-9]*[a-z0-9])$' #Ref - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
  #   required: true

  ####
  ##  OCI Observability & Management Services Configuration
  ####
  
  # Compartment for creating OCI Observability and Management resources
  oci_onm_compartment_ocid:
    type: oci:identity:compartment:id
    required: true
    title: Select compartment for Logging Analytics, Management Agent, and Monitoring service resources
    description: This compartment will be used for creating Dashboards, Log Groups, Entities, Management Agent Keys, Metrics Namespace etc. See https://github.com/oracle-quickstart/oci-kubernetes-monitoring for full list of resources.
    default: compartment_ocid

  # Option to create Logging Analytics
  opt_create_new_la_logGroup: # change this to create new log group
    type: boolean
    title: Check if you want to create a new Log Group
    default: false
    visible:
      not: 
      - livelab_switch

  # OCI Logging Analytics LogGroup OCID of existing LogGroup
  oci_la_logGroup_id:
    type: oci:logan:loggroup:id
    dependsOn:
      compartmentId: ${oci_onm_compartment_ocid}
    title: OCI Logging Analytics Log Group
    description: Log Groups are logical containers for log data, and provide access control for your data using IAM Policies.
    required: true
    visible:
      not:
        - opt_create_new_la_logGroup

  # New Log Group to collect Kubernetes data
  oci_la_logGroup_name:
    type: string
    maxLength: 255
    minLength: 1
    required: true
    title: "OCI Logging Analytics Log Group Name"
    description: "Tip: Give a unique name which can be identified with your cluster name to make it easy to find in Dashboards and Logs Explorer"
    visible:
      and:
        - opt_create_new_la_logGroup
    pattern: '^([a-zA-Z0-9]|[a-zA-Z0-9][\\ a-zA-Z0-9_\-]*[\\a-zA-Z\-0-9_])$'  

  ####
  ##  Kubernetes Deployment Options
  ####
  
  opt_deploy_helm:
    title: "Enable helm release. Creates all (OCI + K8s) resources."
    description: "Uncheck this to skip helm release and only create OCI resources."
    type: boolean
    default: true
    required: true

  # Option to enable/disable metric server installation during helm deployment
  opt_deploy_metric_server:
    type: boolean
    title: Enable Metric Server Installation
    description: Uncheck this if Metric Server is already installed in your cluster.
    default: true
    visible:
      and:
      - opt_deploy_helm
      - not: 
        - livelab_switch

  # Fluentd Base Directory
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: FluentD Working Directory
    description: A directory on the node (with read & write permission) to use for storing Fluentd related data
    default: /var/log
    required: true
    pattern: '^/[\w- /]*$'
    visible:
      and: 
      - opt_deploy_helm
      - not: 
        - livelab_switch  

  ####
  ##  Pre-requisites
  ####

  # Option to create Dynamic Group and Policies
  opt_create_dynamicGroup_and_policies:
    type: boolean
    title: Check to create Dynamic Group and Policies required for deploying monitoring solution
    #description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
    description: "Note: The dynamic group definition must be updated, if node pool(s) and OKE Cluster are in different compartments."
    default: false
    required: true    