# Copyright (c) 2023, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- if eq (include "common.createServiceAccount" .) "true" }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "common.serviceAccount" . }}
  namespace: {{ include "common.namespace" . }}
automountServiceAccountToken: false
{{- end }}

{{- if and (eq (include "common.createServiceAccount" .) "true") (.Values.defaultServiceAccount.enabled | default true) }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: default
  namespace: {{ include "common.namespace" . }}
automountServiceAccountToken: {{ default false .Values.defaultServiceAccount.automountServiceAccountToken }}
{{- end }}
