# Copyright (c) 2023, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: oci-la-fluentd-serviceaccount
  namespace: kube-system

---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: oci-la-fluentd-logs-clusterrole
  namespace: kube-system
rules:
  - apiGroups:
      - ""
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch

---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: oci-la-fluentd-logs-clusterrolebinding
roleRef:
  kind: ClusterRole
  name: oci-la-fluentd-logs-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
  - kind: ServiceAccount
    name: oci-la-fluentd-serviceaccount
    namespace: kube-system
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: oci-la-fluentd-daemonset
  namespace: kube-system
  labels:
    app: oci-la-fluentd-logs
    version: v1
spec:
  selector:
    matchLabels:
      app: oci-la-fluentd-logs
      version: v1
  template:
    metadata:
      labels:
        app: oci-la-fluentd-logs
        version: v1
    spec:
      serviceAccountName: oci-la-fluentd-serviceaccount
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      ## Uncomment the following section if a secret is associated to pull the image
      #imagePullSecrets:
      # Replace this value with actual image pull secrets.
      # Make sure the secret is in the same namespace as defined above.
      #- name: <IMAGE_PULL_SECRET>
      containers:
        - name: oci-la-fluentd-logs
          # Replace this value with actual docker image url
          image: <IMAGE_URL>
          # Replace this value with desired value for image pull policy
          imagePullPolicy: Always
          env:
            - name: K8S_NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
            - name: FLUENTD_CONF
              value: "/var/opt/conf/fluent.conf"  # change as required
            - name: FLUENT_OCI_DEFAULT_LOGGROUP_ID
              # Replace this value with actual logging analytics log group
              value: <OCI_LOGGING_ANALYTICS_LOG_GROUP_ID>
            - name: FLUENT_OCI_NAMESPACE
              # Replace this value with actual namespace of logging analytics
              value: <OCI_TENANCY_NAMESPACE>
            - name: FLUENT_OCI_KUBERNETES_CLUSTER_ID
              # Replace this value with Kubernetes Cluster ID
              value: <KUBERNETES_CLUSTER_OCID>
            - name: FLUENT_OCI_KUBERNETES_CLUSTER_NAME
              # Replace this value with Kubernetes Cluster Name
              value: <KUBERNETES_CLUSTER_NAME>
            - name: OCI_READ_FROM_HEAD
              value: "true" # set it false to collect only current logs
            # Uncomment the following section if using config file base AuthZ instead of default InstancePrincipal based AuthZ.
            # For OKE, recommended AuthZ approach to connect to OCI Logging Analytics APIs is InstancePrincipal.
            #- name: FLUENT_OCI_CONFIG_LOCATION
                #value: "/var/opt/.oci/config"
          ## parameters to limit the memory and requests for the pods
          resources:
            limits:
              memory: 500Mi
            requests:
              cpu: 100m
              memory: 250Mi
          volumeMounts:
            - name: varlog
              mountPath: /var/log
            # Mount all relevant locations depending on where the actual logs presents.
            - name: dockercontainerlogdirectory
              mountPath: /var/log/pods
              readOnly: true
            - name: dockercontainerdatadirectory
              mountPath: /u01/data/docker/containers
              readOnly: true
            # Mount directory where fluentd config exists
            - name: fluentdconfigdir
              mountPath: /var/opt/conf
              readOnly: true
            # Mount directory where oci config exists
            # Uncomment the following section if using config file base AuthZ instead of default InstancePrincipal based AuthZ.
            # For OKE, recommended AuthZ approach to connect to OCI Logging Analytics APIs is InstancePrincipal.
            #- name: ociconfigdir
              #mountPath: /var/opt/.oci
              #readOnly: true
      terminationGracePeriodSeconds: 30
      volumes:
        - name: varlog
          hostPath:
            path: /var/log
        # Mount all relevant locations depending on where the actual logs presents.
        - name: dockercontainerlogdirectory
          hostPath:
            path: /var/log/pods
        - name: dockercontainerdatadirectory
          hostPath:
            path: /u01/data/docker/containers
        # Mount directory where fluentd config exists
        - name: fluentdconfigdir
          configMap:
            # Provide the name of the ConfigMap Name to mount.
            name: oci-la-fluentd-logs-configmap   # change as required
        # Mount directory where oci config exists
        # Uncomment the following section if using config file base AuthZ instead of default InstancePrincipal based AuthZ.
        # For OKE, recommended AuthZ approach to connect to OCI Logging Analytics APIs is InstancePrincipal.
        #- name: ociconfigdir
          #projected:
            #sources:
              #- secret:
                  #name: oci-la-credentials-secret # change as required
