# Copyright (c) 2023, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

source "https://rubygems.org"

gem "oj", "3.16.4"
gem "json", "2.7.2"
gem "fluentd", "1.17.1"
gem "fluent-plugin-oci-logging-analytics", "2.0.6"
gem "fluent-plugin-concat", "~> 2.5.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.4.0"
gem "fluent-plugin-parser-cri", "~> 0.1.1"
gem "fluent-plugin-kubernetes_metadata_filter", "3.5.0"
gem "oci-logging-analytics-kubernetes-discovery", "1.0.2"
gem "fluent-plugin-record-modifier", "2.2.0"
gem "fluent-plugin-cloudwatch-logs", "0.14.3"
gem "fluent-plugin-s3", "1.7.2"
gem "rexml", "3.3.7"
