# Copyright (c) 2023, 2024, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

{{- $authtype := .Values.authtype | lower }}
{{- if eq $authtype "config" }}
apiVersion: v1
kind: Secret
type: Opaque
metadata:
  name: {{ include "logan.resourceNamePrefix" . }}-oci-config
  namespace: {{ include "logan.namespace" . }}
stringData:
  {{- range $key, $value := .Values.oci.configFiles }}
  {{ $key }}: |
    {{- include "common.tplvalues.render" (dict "value" $value "context" $) | nindent 4 }}
  {{- end }}
{{- end}}
