# Copyright (c) 2025, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

---
{{- $authtype := .Values.authtype | lower }}
{{- $imagePullSecrets := .Values.image.imagePullSecrets }}
{{- $resourceNamePrefix := (include "logan.resourceNamePrefix" .) }}
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: {{ $resourceNamePrefix }}-tcpconnect
  namespace: {{ include "logan.namespace" . }}
  labels:
    app: {{ $resourceNamePrefix }}-tcpconnect
    version: v1
spec:
  selector:
    matchLabels:
      app: {{ $resourceNamePrefix }}-tcpconnect
      version: v1
  template:
    metadata:
      labels:
        app: {{ $resourceNamePrefix }}-tcpconnect
        version: v1
    spec:
      serviceAccountName: {{ include "logan.serviceAccount" . }}
      tolerations:
      - key: node-role.kubernetes.io/master
        effect: NoSchedule
      - key: node-role.kubernetes.io/control-plane
        effect: NoSchedule
      {{- if $imagePullSecrets }}
      imagePullSecrets:
      - name: {{ .Values.image.imagePullSecrets }}
      {{- end}}
      containers:
      - name: {{ $resourceNamePrefix }}-tcpconnect
        image: {{ .Values.image.url }}
        command:
        - /bin/bash
        - -c
        - --
        args:
        - /usr/bin/tcpconnect -e
        - -i {{ .Values.fluentd.kubernetesSystem.logs.tcpconnect.interval }}
        env:
        - name: K8S_NODE_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: spec.nodeName
        resources:
          requests:
            cpu: 50m
            memory: 50Mi
        imagePullPolicy: {{ default "IfNotPresent" .Values.image.imagePullPolicy }}
        securityContext:
          capabilities:
            add:
            - CAP_BPF
          privileged: true
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        tty: true
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30