# Copyright (c) 2026, Oracle and/or its affiliates.
# Licensed under the Universal Permissive License v1.0 as shown at https://oss.oracle.com/licenses/upl.

---
{{- if .Values.enableTCPConnectLogs }}
{{- $resourceNamePrefix := (include "logan.resourceNamePrefix" .) }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $resourceNamePrefix }}-tcpconnect
  namespace: {{ include "logan.namespace" . }}
  labels:
    app: {{ $resourceNamePrefix }}-logan-tcpconnect
    app.kubernetes.io/name: {{ $resourceNamePrefix }}-logan-tcpconnect
automountServiceAccountToken: false
{{- end }}
