apiVersion: v1
kind: ServiceAccount
metadata:
  name: mgmtagent-serviceaccount
  namespace: {{ default "mgmtagent" .Values.namespace }}
  labels:
    k8s-app: mgmtagent
    version: v1

---

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: mgmtagent-clusterrole
  namespace: {{ default "mgmtagent" .Values.namespace }}
rules:
  - apiGroups:
      - ""
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch
  - nonResourceURLs: ["/metrics"]
    verbs: ["get"]
  - apiGroups:
      - metrics.k8s.io
    resources:
      - '*'
    verbs:
      - get
      - list
      - watch

---

kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: mgmtagent
roleRef:
  kind: ClusterRole
  name: mgmtagent-clusterrole
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: mgmtagent-serviceaccount
  namespace: {{ default "mgmtagent" .Values.namespace }}