source "https://rubygems.org"

gem "fluentd", "1.14.1"
gem "fluent-plugin-oci-logging-analytics", "2.0.0"
gem "fluent-plugin-concat", "~> 2.5.0"
gem "fluent-plugin-rewrite-tag-filter", "~> 2.4.0" 
gem "fluent-plugin-parser-cri", "~> 0.1.1"
gem "fluent-plugin-kubernetes_metadata_filter", "2.9.1"
gem "fluent-plugin-kubernetes-objects", "~> 1.1.7"
