title: OCI Kubernetes Monitoring Solution
description: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
informationalText: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: quickstart

locale: "en"

variableGroups:
  - title: "Defualt inputs"
    variables:
      - tenancy_ocid
      - region
      - enable_local_testing
      - enable_helm_release
      - enable_dashboard_import
    visible: false

  - title: "OKE Cluster Information"
    variables:
      - oke_cluster_compartment
      - oke_cluster_ocid
      - oke_cluster_name
      - container_image_url
      - kubernetes_namespace
      - opt_create_kubernetes_namespace

  - title: "OCI Logging Analytics Information"
    variables:
    - opt_use_existing_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name
    - oci_la_namespace
    - oci_la_compartment_ocid

  - title: "Fluentd Configuration"
    variables:
      - fluentd_baseDir_path

variables:
  oke_cluster_compartment:
    type: oci:identity:compartment:id
    required: true    
    title: OKE Cluster Compartment
    default: compartment_ocid

  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_cluster_compartment}
    title: OKE Cluster
    required: true

  # string field
  oke_cluster_name:
    type: string
    minLength: 1
    maxLength: 255
    title: OKE Cluster Name
    required: true

  # string field
  container_image_url:
    type: string
    minLength: 1
    maxLength: 255
    title: OCI LA Fluentd Container Image
    description: Image URL of OCI LA Fluentd Container
    required: true

  # string field
  kubernetes_namespace:
    type: string
    minLength: 1
    maxLength: 255
    title: Kubernetes Namespace
    description: Kubernetes Namespace in which the monitoring solution to be deployed
    default: kube-system
    required: true

  # renders variable as a check box
  opt_create_kubernetes_namespace:
    type: boolean
    title: If checked, entered namespace will be created if it doesn't exist already
    description: UnChecking this option can lead to failure when entered namespace doesn't exist in cluster
    default: true
    required: true

  # string field
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: Fluentd Base Directory
    description: Base directory on the node (with read write permission) to store fluentd plugin's related data
    default: /var/log
    required: true

  # string field
  oci_la_namespace:
    type: string
    maxLength: 30
    minLength: 5
    title: OCI Logging Analytics Service Namespace
    description: "Visit: https://cloud.oracle.com/loganalytics/service to find Logging Analytics service namespace"
    required: true

  oci_la_compartment_ocid:
    type: oci:identity:compartment:id
    required: true    
    title: OCI Logging Analytics Compartment
    description: Compartment for creating dashboards and saved-searches
    default: compartment_ocid

  # renders variable as a check box
  opt_use_existing_la_logGroup:
    type: boolean
    title: Use an existing Log Group to collect Kubernetes Data ?
    description: "UnCheck to create a new Logging Analytics LogGroup instead"
    default: true
    required: true

  # string field
  oci_la_logGroup_id:
    type: string
    maxLength: 255
    minLength: 1
    title: OCI Logging Analytics LogGroup OCID
    description: The LogGroup in which the collected log data to be stored
    required: true
    visible: 
      and: 
        - opt_use_existing_la_logGroup

  oci_la_logGroup_name:
    type: string
    maxLength: 30
    minLength: 5
    required: true    
    title: OCI Logging Analytics Log Group
    description: Note - LogGroup Names must be unique in a tenant
    visible: 
      not: 
        - opt_use_existing_la_logGroup
    pattern: "^[a-zA-Z0-9]+$"