title: OCI Kubernetes Monitoring Solution
description: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
informationalText: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: quickstart

locale: "en"

variableGroups:
  - title: "configuration inputs"
    variables:
      - auth_tenancy_ocid
      - tenancy_ocid
      - region
      - user_ocid
      - private_key_path
      - fingerprint
      - enable_helm_release
      - enable_dashboard_import
      - enable_la_resources
    visible: false

  - title: "Dynamic Group and Policies"
    variables:
      - opt_create_dynamicGroup_and_policies

  - title: "OKE Cluster Information"
    variables:
      - oke_compartment_ocid
      - oke_cluster_ocid
      - container_image_url
      - kubernetes_namespace
      - opt_create_kubernetes_namespace

  - title: "OCI Logging Analytics Information"
    variables:
    - oci_la_compartment_ocid
    - opt_use_existing_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name

  - title: "Fluentd Configuration"
    variables:
      - fluentd_baseDir_path

variables:

  ####
  ##  Dynamic Group and Policies
  ####

  # Option to create Dynamic Group and Policies
  opt_create_dynamicGroup_and_policies:
    type: boolean
    title: Create required Dynamic Group and Policies
    description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
    default: true
    required: true

  ####
  ##  OKE Cluster Information
  ####

  # OKE Cluster Compartment
  oke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true    
    title: OKE Cluster Compartment
    default: compartment_ocid

  # OKE Cluster OCID
  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_compartment_ocid}
    title: OKE Cluster
    required: true

  # OCI LA Fluentd Container Image
  container_image_url:
    type: string
    minLength: 1
    maxLength: 255
    title: OCI LA Fluentd Container Image
    description: Image URL of OCI LA Fluentd Container
    pattern: '^[\S]+$'
    required: true

  # Kubernetes Namespace
  kubernetes_namespace:
    type: string
    minLength: 1
    maxLength: 63
    title: Kubernetes Namespace
    description: Kubernetes Namespace in which the monitoring solution to be deployed
    default: kube-system
    pattern: '^([a-z0-9]|[a-z][a-z\-0-9]*[a-z0-9])$' #Ref - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
    required: true

  # Option to create Kubernetes Namespace
  opt_create_kubernetes_namespace:
    type: boolean
    title: Create namespace, if doesn't exist
    description: Note- Un-checking this option can lead to failure when namespace doesn't exist in cluster
    default: true
    required: true

  ####
  ##  OCI Logging Analytics Information
  ####

  # Compartment for creating dashboards and saved-searches
  oci_la_compartment_ocid:
    type: oci:identity:compartment:id
    required: true    
    title: OCI Logging Analytics Compartment
    description: Compartment for creating dashboards, saved-searches and logGroup
    default: compartment_ocid

  # Option to create Logging Analytics
  opt_use_existing_la_logGroup:
    type: boolean
    title: Select an existing LogGroup
    description: "Un-check to create a new LogGroup"
    default: true
    required: true

  # OCI Logging Analytics LogGroup OCID
  oci_la_logGroup_id:
    type: oci:logan:loggroup:id
    dependsOn:
      compartmentId: ${oci_la_compartment_ocid}
    title: OCI Logging Analytics LogGroup
    description: LogGroup to store collected logs
    required: true
    visible: 
      and: 
        - opt_use_existing_la_logGroup

  # New Log Group to collect Kubernetes data
  oci_la_logGroup_name:
    type: string
    maxLength: 255
    minLength: 1
    required: true    
    title: "*New* OCI Logging Analytics LogGroup Name"
    description: Note - LogGroup name must be unique in a tenant
    visible: 
      not: 
        - opt_use_existing_la_logGroup
    pattern: '^([a-zA-Z0-9]|[a-zA-Z0-9][\\ a-zA-Z0-9_\-]*[\\a-zA-Z\-0-9_])$'

  ####
  ##  Fluentd Configuration
  ####

  # Fluentd Base Directory
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: Fluentd Base Directory
    description: Base directory on the node (with read & write permission) to store fluentd plugin's related data
    default: /var/log
    required: true
    pattern: '^/[\w- /]*$'