title: OCI Kubernetes Monitoring Solution
description: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
informationalText: Monitoring Solution for Kubernetes offered by OCI Logging Analytics
schemaVersion: 1.1.0
version: "20221004"

# URL of Logo Icon used on Application Information tab. Logo must be 130x130 pixels.
# (Optional)
#logoUrl: https://cloudmarketplace.oracle.com/marketplace/content?contentId=53066708

source:
  type: marketplace  # enum - marketplace, quickstart or web

locale: "en"

variableGroups:
  - title: "configuration inputs"
    variables:
      - auth_tenancy_ocid
      - tenancy_ocid
      - region
      - user_ocid
      - private_key_path
      - fingerprint
      - enable_helm_debugging
      - enable_dashboard_import
      - enable_helm_release
      - boat_auth
      - boat_tenancy_ocid
      - compartment_ocid
    visible: false

  - title: "Pre-requisites"
    variables:
      - opt_create_dynamicGroup_and_policies
    visible: 
      and: 
        - enable_helm_release

  - title: "OKE Cluster Information"
    variables:
      - oke_compartment_ocid
      - oke_cluster_ocid
      - kubernetes_namespace
      - opt_create_kubernetes_namespace
    visible: 
      and: 
        - enable_helm_release

  - title: "OCI Logging Analytics Information"
    variables:
    - oci_la_compartment_ocid
    - opt_create_new_la_logGroup
    - oci_la_logGroup_id
    - oci_la_logGroup_name
    visible: 
      and: 
        - enable_helm_release

  - title: "Fluentd Configuration"
    variables:
      - container_image_url
      - fluentd_baseDir_path
    visible: 
      and:
        - enable_helm_release

variables:

  ####
  ##  Deployment Options
  ####

  # Option to install helm chart
  enable_helm_release:
    type: boolean
    title: Deploy Kubernetes Monitoring Solution
    description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring"
    default: true
    required: true

  ####
  ##  Pre-requisites
  ####

  # Option to create Dynamic Group and Policies
  opt_create_dynamicGroup_and_policies:
    type: boolean
    title: Create Dynamic Group and Policies required for Kubernetes Monitoring Solution (Un-check if created manually)
    #description: "Ref: https://github.com/oracle-quickstart/oci-kubernetes-monitoring#pre-requisites"
    description: "Note: The auto-created dynamic group may need changes, if node pool(s) compartment is different than cluster compartment."
    default: true
    required: true

  ####
  ##  OKE Cluster Information
  ####

  # OKE Cluster Compartment
  oke_compartment_ocid:
    type: oci:identity:compartment:id
    required: true    
    title: OKE Cluster Compartment
    default: compartment_ocid

  # OKE Cluster OCID
  oke_cluster_ocid:
    type: oci:container:cluster:id
    dependsOn:
      compartmentId: ${oke_compartment_ocid}
    title: OKE Cluster
    required: true

  # Kubernetes Namespace
  kubernetes_namespace:
    type: string
    minLength: 1
    maxLength: 63
    title: Kubernetes Namespace
    description: Kubernetes Namespace in which the monitoring solution to be deployed
    default: kube-system
    pattern: '^([a-z0-9]|[a-z][a-z\-0-9]*[a-z0-9])$' #Ref - https://kubernetes.io/docs/concepts/overview/working-with-objects/names/#dns-label-names
    required: true

  # Option to create Kubernetes Namespace
  opt_create_kubernetes_namespace:
    type: boolean
    title: Create namespace, if doesn't exist
    description: "Note: Un-checking this option can lead to failure when namespace doesn't exist in cluster"
    default: true
    required: true

  ####
  ##  OCI Logging Analytics Information
  ####

  # Compartment for creating dashboards and logGroup
  oci_la_compartment_ocid:
    type: oci:identity:compartment:id
    required: true    
    title: OCI Logging Analytics Compartment
    description: Compartment to store Logging Analytics dashboards and logGroup
    default: compartment_ocid

  # Option to create Logging Analytics
  opt_create_new_la_logGroup: # change this to create new log group
    type: boolean
    title: Create a new LogGroup
    default: false

  # OCI Logging Analytics LogGroup OCID of existing LogGroup
  oci_la_logGroup_id:
    type: oci:logan:loggroup:id
    dependsOn:
      compartmentId: ${oci_la_compartment_ocid}
    title: OCI Logging Analytics LogGroup
    description: LogGroup to store collected logs
    required: true
    visible: 
      not: 
        - opt_create_new_la_logGroup

  # New Log Group to collect Kubernetes data
  oci_la_logGroup_name:
    type: string
    maxLength: 255
    minLength: 1
    required: true    
    title: "OCI Logging Analytics LogGroup Name"
    description: "Note: LogGroup name must be unique in a tenant"
    visible:
      and: 
        - opt_create_new_la_logGroup
    pattern: '^([a-zA-Z0-9]|[a-zA-Z0-9][\\ a-zA-Z0-9_\-]*[\\a-zA-Z\-0-9_])$'

  ####
  ##  Fluentd Configuration
  ####

  # OCI LA Fluentd Container Image
  container_image_url:
    type: string
    minLength: 1
    maxLength: 255
    title: OCI Logging Analytics fluentd container image
    default: iad.ocir.io/ax1wgjs6b2vc/oci_la_fluentd:ol8-1.1
    pattern: '^[\S]+$'
    required: true
    description: "Note: Default value is not recommended for production usage. You may need to build your own image using https://github.com/oracle-quickstart/oci-kubernetes-monitoring#docker-image"

  # Fluentd Base Directory
  fluentd_baseDir_path:
    type: string
    maxLength: 255
    minLength: 1
    title: Fluentd Base Directory
    description: Base directory on the node (with read & write permission) to store fluentd plugin's related data
    default: /var/log
    required: true
    pattern: '^/[\w- /]*$'